Enhanced README.md
fossasia/pslab-webapp-legacy pull request #106
Opened 2020-01-05 13:15 UTC by samjain2907

Fixes #[Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]
#105 
Changes: [Add here what changes were made in this issue and if possible provide links.]
Enhanced the README.md file and fixed the typing errors.
Screenshots for the change:

2020-01-28 16:54 UTC, Dishebh requested changes
Kindly check for the travis ci issues. Why the build is failing?

2020-02-05 04:48 UTC, samjain2907 commented
> Kindly check for the travis ci issues. Why the build is failing?

It was just a simple README change. I don't know why the build is failing. Please can you help me.

2020-02-07 09:04 UTC, Dishebh commented
> > Kindly check for the travis ci issues. Why the build is failing?
> 
> It was just a simple README change. I don't know why the build is failing. Please can you help me.

Seems to me the command `bower install` is falling. 
https://stackoverflow.com/questions/30485100/npm-install-bower-install-exited-with-error-code-1

See if the above link helps somehow.

2020-02-08 04:56 UTC, Pipe-Runner approved these changes

2026-07-31 11:41 UTC, closed without merging